from PyQt5.QtWidgets import QCheckBox, QDoubleSpinBox, QGridLayout, QGroupBox, QLabel, QLineEdit, QPushButton, QSpinBox, QVBoxLayout


def build_detection_panel(tool):
    detect_box = QGroupBox("目标识别标注")
    detect_layout = QVBoxLayout()
    detect_layout.setSpacing(12)
    detect_box.setMinimumWidth(500)

    tool.det_classes_edit = QLineEdit(",".join(tool.det_class_names))
    tool.det_classes_edit.setMinimumWidth(320)
    tool.det_classes_edit.setPlaceholderText("兼容批量编辑：用英文逗号分隔类别后点应用")
    btn_apply_classes = QPushButton("应用类别")
    btn_apply_classes.clicked.connect(tool.apply_detection_classes)
    btn_add_class = QPushButton("新增类别")
    btn_add_class.clicked.connect(tool.add_detection_class_inline)
    btn_delete_class = QPushButton("删除当前类别")
    btn_delete_class.clicked.connect(tool.delete_detection_class)
    class_grid = QGridLayout()
    class_grid.setHorizontalSpacing(8)
    class_grid.addWidget(QLabel("目标类别"), 0, 0)
    class_grid.addWidget(tool.det_classes_edit, 0, 1)
    class_grid.addWidget(btn_apply_classes, 0, 2)
    class_grid.addWidget(btn_add_class, 1, 1)
    class_grid.addWidget(btn_delete_class, 1, 2)
    detect_layout.addLayout(class_grid)

    tool.det_class_grid = QGridLayout()
    tool.det_class_grid.setSpacing(8)
    detect_layout.addLayout(tool.det_class_grid)
    tool.det_class_buttons = []
    tool.rebuild_detection_class_buttons()

    tool.model_path_edit = QLineEdit(tool.model_path)
    tool.model_path_edit.setMinimumWidth(320)
    btn_browse_model = QPushButton("选择模型")
    btn_browse_model.clicked.connect(tool.choose_model_path)
    btn_load_model = QPushButton("加载模型")
    btn_load_model.clicked.connect(tool.load_yolo_model)
    model_grid = QGridLayout()
    model_grid.setHorizontalSpacing(8)
    model_grid.setVerticalSpacing(8)
    model_grid.addWidget(QLabel("识别模型"), 0, 0)
    model_grid.addWidget(tool.model_path_edit, 0, 1, 1, 2)
    model_grid.addWidget(btn_browse_model, 1, 1)
    model_grid.addWidget(btn_load_model, 1, 2)
    detect_layout.addLayout(model_grid)

    tool.yolo_review_dir_edit = QLineEdit(tool.yolo_review_dir or tool.output_dir)
    tool.yolo_review_dir_edit.setMinimumWidth(320)
    tool.yolo_review_dir_edit.setPlaceholderText("YOLO数据集根目录，包含 images/train 和 labels/train")
    btn_browse_yolo_review = QPushButton("选择YOLO数据集")
    btn_browse_yolo_review.clicked.connect(tool.choose_yolo_review_dir)
    btn_open_yolo_review = QPushButton("打开并编辑标注")
    btn_open_yolo_review.clicked.connect(tool.open_yolo_review_dataset)
    yolo_review_grid = QGridLayout()
    yolo_review_grid.setHorizontalSpacing(8)
    yolo_review_grid.setVerticalSpacing(8)
    yolo_review_grid.addWidget(QLabel("查看YOLO标注"), 0, 0)
    yolo_review_grid.addWidget(tool.yolo_review_dir_edit, 0, 1, 1, 2)
    yolo_review_grid.addWidget(btn_browse_yolo_review, 1, 1)
    yolo_review_grid.addWidget(btn_open_yolo_review, 1, 2)
    detect_layout.addLayout(yolo_review_grid)

    detect_ops = QGridLayout()
    detect_ops.setHorizontalSpacing(8)
    detect_ops.setVerticalSpacing(8)
    tool.conf_spin = QDoubleSpinBox()
    tool.conf_spin.setDecimals(2)
    tool.conf_spin.setRange(0.01, 0.99)
    tool.conf_spin.setSingleStep(0.05)
    tool.conf_spin.setValue(0.25)
    tool.auto_replace_checkbox = QCheckBox("自动检测前清空")
    tool.auto_replace_checkbox.setChecked(True)
    btn_auto_detect = QPushButton("自动识别目标")
    btn_auto_detect.clicked.connect(tool.auto_detect_current_image)
    btn_undo = QPushButton("删除最后目标")
    btn_undo.clicked.connect(tool.delete_last_detection_box)
    btn_clear = QPushButton("清空目标框")
    btn_clear.clicked.connect(tool.clear_detection_boxes)
    detect_ops.addWidget(QLabel("置信度"), 0, 0)
    detect_ops.addWidget(tool.conf_spin, 0, 1)
    detect_ops.addWidget(tool.auto_replace_checkbox, 0, 2, 1, 2)
    detect_ops.addWidget(btn_auto_detect, 1, 0, 1, 2)
    detect_ops.addWidget(btn_undo, 1, 2)
    detect_ops.addWidget(btn_clear, 1, 3)
    detect_layout.addLayout(detect_ops)

    link_grid = QGridLayout()
    link_grid.setHorizontalSpacing(8)
    link_grid.setVerticalSpacing(8)
    tool.link_source_edit = QLineEdit("knob")
    tool.link_target_edit = QLineEdit("plate")
    tool.max_distance_spin = QSpinBox()
    tool.max_distance_spin.setRange(1, 10000)
    tool.max_distance_spin.setValue(300)
    tool.max_distance_spin.valueChanged.connect(tool.update_detection_overlay)
    tool.show_links_checkbox = QCheckBox("显示连线")
    tool.show_links_checkbox.setChecked(True)
    tool.show_links_checkbox.stateChanged.connect(tool.toggle_connection_overlay)
    btn_check = QPushButton("检查标注")
    btn_check.clicked.connect(tool.check_annotations)
    link_grid.addWidget(QLabel("源类别"), 0, 0)
    link_grid.addWidget(tool.link_source_edit, 0, 1)
    link_grid.addWidget(QLabel("关联目标类别"), 0, 2)
    link_grid.addWidget(tool.link_target_edit, 0, 3)
    link_grid.addWidget(QLabel("最大距离(px)"), 1, 0)
    link_grid.addWidget(tool.max_distance_spin, 1, 1)
    link_grid.addWidget(tool.show_links_checkbox, 1, 2)
    link_grid.addWidget(btn_check, 1, 3)
    detect_layout.addLayout(link_grid)

    tool.det_info = QLabel("检测框：0")
    tool.det_info.setWordWrap(True)
    tool.det_info.setProperty("class", "hint")
    detect_layout.addWidget(tool.det_info)
    detect_box.setLayout(detect_layout)
    return detect_box
